### ISSUE TITLE
書籍内で紹介しているURLのアップデート

### ISSUE THREAD

**Issue by Tiryoh** [youtalk/get-started-ros2#19]
書籍内で紹介しているサイトの一部でリンクがたどれない状態になっていました。
[eratta.md](https://github.com/youtalk/get-started-ros2/blob/354ed0777326d1b75e1db2bc4fa35604cf3f21e0/eratta.md)に載っていないようでしたので、報告いたします。

p. 69 3-5-2 colconの使い方
before:
https://github.com/ros2/ros2/wiki/Colcon-Tutorial
after:
https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/

**Comment by youtalk** [comment]
ありがとうございます。正誤表を更新しました。
