### ISSUE TITLE
3-7-2：同期処理をコメントインするとコンパイルエラーが出る

### ISSUE THREAD

**Issue by ShotaAk** [youtalk/get-started-ros2#22]
3-7-2（テキストp84）のclient_async.cpp の非同期処理をコメントアウトして、
同期処理をコメントインしましたが、コンパイルでエラーが発生しました。

一つは、spin_until_future_completeの引数`node`が宣言されていないこと

https://github.com/youtalk/get-started-ros2/blob/c393731edf645ddda0c033a0214584ed9a899fb7/ros2/hello_world/src/client_async.cpp#L62

もう一つは、future_resultのget()にアロー演算子使っていることです。

https://github.com/youtalk/get-started-ros2/blob/c393731edf645ddda0c033a0214584ed9a899fb7/ros2/hello_world/src/client_async.cpp#L65

---

トライアンドエラーでコードを直してみたら、コンパイルでき、動くようになりました。
（手探りで見つけたコードなので、プルリクにはしてません・・・）

```diff
      auto future_result = client_->async_send_request(request);
+      if (rclcpp::spin_until_future_complete(this->get_node_base_interface(), future_result) ==
-      if (rclcpp::spin_until_future_complete(node, future_result) ==
          rclcpp::executor::FutureReturnCode::SUCCESS) {
        RCLCPP_INFO(this->get_logger(), "%s",
+                    future_result.get()->result ? "true" : "false");
-                    future_result->get().result ? "true" : "false");                  
        rclcpp::shutdown();
```

が、rclcpp::shutdown()で怒られるようになりました。
（コンストラクタが実行し終わる前にshutdownを呼んでるから　ですかね？）

```
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  Failed to create interrupt guard condition in Executor constructor: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-dashing-rcl-0.7.6/src/rcl/guard_condition.c:69
```
---

ROS2本、サンプルコードもあって読みやすいです :+1:

**Comment by youtalk** [comment]
ご報告ありがとうございます。プログラムはCIでビルド確認をしているのですが、コメントアウトしているこちらの部分はCI確認できておらず、内容が古いままになっておりました。2版で修正します。

**Comment by youtalk** [comment]
#23 で修正しました。CIで同期版のソースコードもビルド確認するようにしたので、これ以降は同じ問題が起こらなくなると思います。
