### ISSUE TITLE
p6 gazeboのインストール

### ISSUE THREAD

**Issue by tmdoi** [youtalk/get-started-ros2#25]
こんばんわ

以下のコマンド実行時にエラーが出ました。
curl -sSL http://get.gazebosim.org | sh

JetsonNanoにインストールしようとしているのが原因でしょうか？

〜〜〜
=======================================================
GAZEBO INSTALLATION SCRIPT
=======================================================

This script is installing the latest stable version of
Gazebo Simulator available from your package manager

In Ubuntu this script will setup the osrfoundation
repository to install the latest package available

+ sudo -E sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
Executing: /tmp/apt-key-gpghome.k6zpR2jlVK/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
gpg: 鍵67170598AF249743:"OSRF Repository (OSRF Repository GPG key) <osrfbuild@osrfoundation.org>"変更なし
gpg: 処理数の合計: 1
gpg:              変更なし: 1
+ sudo -E sh -c mkdir -p /etc/apt/sources.list.d
+ sudo -E sh -c echo deb http://packages.osrfoundation.org/gazebo/ubuntu bionic main > /etc/apt/sources.list.d/gazebo-stable.list
+ sudo -E sh -c sleep 3; apt-get update; apt-get install -y -q libgazebo9-dev
取得:1 file:/var/cuda-repo-10-0-local-10.0.166  InRelease
無視:1 file:/var/cuda-repo-10-0-local-10.0.166  InRelease
取得:2 file:/var/visionworks-repo  InRelease
無視:2 file:/var/visionworks-repo  InRelease
取得:3 file:/var/visionworks-sfm-repo  InRelease
無視:3 file:/var/visionworks-sfm-repo  InRelease
取得:4 file:/var/visionworks-tracking-repo  InRelease
無視:4 file:/var/visionworks-tracking-repo  InRelease
取得:5 file:/var/cuda-repo-10-0-local-10.0.166  Release [574 B]
取得:6 file:/var/visionworks-repo  Release [1,999 B]
取得:5 file:/var/cuda-repo-10-0-local-10.0.166  Release [574 B]                
取得:7 file:/var/visionworks-sfm-repo  Release [2,003 B]                       
取得:6 file:/var/visionworks-repo  Release [1,999 B]                           
取得:7 file:/var/visionworks-sfm-repo  Release [2,003 B]                       
取得:8 file:/var/visionworks-tracking-repo  Release [2,008 B]                  
取得:8 file:/var/visionworks-tracking-repo  Release [2,008 B]                  
ヒット:9 http://packages.osrfoundation.org/gazebo/ubuntu bionic InRelease      
ヒット:11 http://packages.ros.org/ros/ubuntu bionic InRelease                  
ヒット:13 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                
ヒット:15 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
ヒット:17 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
ヒット:18 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
パッケージリストを読み込んでいます... 完了                  
パッケージリストを読み込んでいます...
依存関係ツリーを作成しています...
状態情報を読み取っています...
インストールすることができないパッケージがありました。おそらく、あり得
ない状況を要求したか、(不安定版ディストリビューションを使用しているの
であれば) 必要なパッケージがまだ作成されていなかったり Incoming から移
動されていないことが考えられます。
以下の情報がこの問題を解決するために役立つかもしれません:

以下のパッケージには満たせない依存関係があります:
 libgazebo9-dev : 依存: gazebo9-common (= 9.8.0-1~bionic) しかし、9.11.0-1~bionic はインストールされようとしています
                  依存: gazebo9-plugin-base (= 9.8.0-1~bionic) しかし、9.0.0+dfsg5-3ubuntu1+ppa2 はインストールされようとしています
E: 問題を解決することができません。壊れた変更禁止パッケージがあります。

**Comment by youtalk** [comment]
すみませんが、ROSやGazeboのインストールなどに関しては、下記公式ROS, Gazeboの質問サイトをご利用ください。Jetson Nanoなど、固有の環境を僕が再現することは困難です。
- http://answers.gazebosim.org/questions/
- https://discourse.ros.org/c/local/japan
