### ISSUE TITLE
図3-2中のrmwについて

### ISSUE THREAD

**Issue by MoriKen254** [youtalk/get-started-ros2#26]
お疲れさまです。本書には大変助けられております。

さて、図3-2中の図に「通信ミドルウェア API」の記述がございますして、そこに「rmv」と記載されているのですが、正しくは「rmw」ではないかと思い、ご報告させて頂きました。

![image](https://user-images.githubusercontent.com/12078261/65953972-11f92c00-e480-11e9-8c58-014de010a59c.png)

Kindle版、初版 第1刷が対象です。細かい指摘で恐縮です。確認いただければ幸いです。

**Comment by youtalk** [comment]
ありがとうございます。後ほど正誤表に反映します。

**Comment by youtalk** [comment]
すでに正誤表にありました。 https://www.youtalk.jp/get-started-ros2/eratta.html
