### ISSUE TITLE
ページ73のCMakeLists.txtについて

### ISSUE THREAD

**Issue by tmparticle** [youtalk/get-started-ros2#28]
この本でROS2の勉強を始めた者です。
CMakeLists.txtの14行目ですが、"rclcpp"だけでなく"hello_world_msgs"も加えてやらないとコンパイルが上手く行かなかったのでお知らせします。

**Comment by youtalk** [comment]
ご報告ありがとうございます。こちらは https://github.com/youtalk/get-started-ros2/issues/27 にて、修正を行いましたので、ご確認ください。
