### ISSUE TITLE
typo(日本語表現)

### ISSUE THREAD

**Issue by physalily** [youtalk/get-started-ros2#33]
P114 4-3-5 ライフサイクル対応listener実装
見出しから6行目： これまでどうり　→　これまで通り（これまでどおり）

正誤表になかったので報告します。
（自分でも日本語的にあっているのかそうでないのかわからなくなってきたので、間違っていたら見なかったことにしてください。）

**Comment by youtalk** [comment]
ありがとうございます。正誤表に反映しました。
https://github.com/youtalk/get-started-ros2/commit/070e8d85ce858ed8b2a3ec7184af799cdb33a8fb
