### ISSUE TITLE
talker_with_service_param でノード起動時にはログ出力に decoration_ の値が反映されない

### ISSUE THREAD

**Issue by hideakitai** [youtalk/get-started-ros2#38]
素晴らしい書籍とサンプルコードをありがとうございます。
一点、タイトルのような現象が起きていました。後ほど一案として Pull Request をお送りします。

### 環境

- Ubuntu 20.04 LTS
- ROS2 Foxy

### 現象

`talker_with_service_param` ノードに CLI, launch (--ros-args), launch (yaml) でパラメータ初期値を与えてもログ出力に反映されない。パラメータサーバには反映されているようだが、上記のように初期値を与えても `decoration_` を更新するハンドラが呼ばれていないため、ログ出力に反映されていない模様。

**Comment by youtalk** [comment]
ご報告ありがとうざいます！
もしかするとrclcpp自体のバグかもしれません。まずは本家のソースコードやデモコードを確認してみますので、しばらくお待ちください。

**Comment by youtalk** [comment]
https://github.com/youtalk/get-started-ros2/pull/40 の方法で修正できました。

**Comment by hideakitai** [comment]
なるほど、 `declare_parameter` の返り値を使えば良いのですね。ありがとうございました！
