### ISSUE TITLE
hello_world_msgs/srv/set_message.hpp

### ISSUE THREAD

**Issue by macchon** [youtalk/get-started-ros2#41]
3-7-1のtalker_with_service.cppのところをやっていますが
hello_world_msgs/srv/set_message.hppというファイルがないように思います
SetMessage.srvというファイルはあります
cmakeとかC++自体に全然慣れていないので勘違いかもしれませんが

**Comment by youtalk-pfr** [comment]
@macchon ご連絡ありがとうございます。
set_message.hppはcolcon buildするとSetMessage.srvの定義に従って自動生成されます。お試しください。

**Comment by youtalk** [comment]
@macchon ご連絡ありがとうございます。
set_message.hppはcolcon buildするとSetMessage.srvの定義に従って自動生成されます。お試しください。

**Comment by macchon** [comment]
ああ、自動生成されるのですね
勉強のためにソースを順番に自分で書いていたので気が付きませんでした
ありがとうございました。
