### ISSUE TITLE
表4-11および表4-12について

### ISSUE THREAD

**Issue by tomiy-0x62** [youtalk/get-started-ros2#47]
「4-5-3 QoS互換性」に記載されている表4-11および表4-12について、表の右端にある「値」の列は何を意味しているのでしょうか？例えば、送信側がReliable、受信側がBest effortに設定されていた場合、送信側はBest effortの振る舞いをするという理解でよろしいでしょうか？

**Comment by youtalk** [comment]
いえ、この場合は受信側だけが影響します。つまり、
```
送信側がReliable、受信側がBest effortに設定されていた場合
```
は受信側がBest effortのままです。送信側はただ送信しているだけですので、設定も変わらず、Reliableのままです。仮に他の受信者がReliableの場合、送受信とものReliableになります。
特別なのは送信が欠損を許すBest effortなのに、受信側がすべて受信するReliableに設定してしまうと通信が始まりません。
